sudo: required

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-5.0
            - libstdc++-7-dev

install: export CXX="clang++-5.0" CC="clang-5.0"

language: cpp

compiler:
  - clang

script:
  - mkdir out
  - cd out
  - cmake ..
  - make
  - ./dux_base_test_bin