sudo: required

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-6.0
            - libstdc++-7-dev

install: export CXX="clang++-6.0" CC="clang-6.0"

language: cpp

compiler:
  - clang

script:
  - mkdir out
  - cd out
  - cmake ../test/
  - make
  - ./dux_base_test